export * from "./response/get-all-domains.response.dto.";
export * from "./response/broadcast-sheet.response.dto";
export * from "./response/get-broadcasts-list.response.dto";
export * from "./response/update-cell.response.dto";
export * from "./response/approve-broadcast-sheet.response.dto";
export * from "./response/approve-broadcast.response.dto";
export * from "./response/get-broadcast-domains-list.response.dto";
export * from "./response/broadcast-sheet.response.dto";
export * from "./response/calculated-broadcast-sends.response.dto";
export * from "./response/copy-sends-count.response.dto";
export * from "./response/partner-sends.response.dto";
export * from "./response/product-sends.response.dto";
export * from "./response/day-broadcast-sends.response.dto";
export * from "./response/get-broadcasts-sends.response.dto";

export * from "./request/make-broadcast.request.dto";
export * from "./request/approve-broadcast-sheet.request.dto";
export * from "./request/approve-broadcast.request.dto";
export * from "./request/get-broadcast-domains-list.request.dto";
